Repository cloud-pi-native/socle, pull requests merged in 2024-07, with the labels that each got.

#266 fix: :ambulance: add vault jwt auth config
  README.md
  roles/vault/tasks/post-install.yml
Labels: bug, enhancement

#158 feat: :wrench: Add overwrite limit for gitlab runner
  roles/gitlab-runner/templates/values/00-main.j2
  roles/socle-config/files/cr-conf-dso-default.yaml
  roles/socle-config/files/crd-conf-dso.yaml
Labels: enhancement

#267 feat: :zap: use cnpg cluster for gitlab
  roles/gitlab/tasks/main.yaml
  roles/gitlab/templates/pg-cluster-gitlab-backup.yaml.j2
  roles/gitlab/templates/pg-cluster-gitlab-nodeport.yaml.j2
  roles/gitlab/templates/pg-cluster-gitlab.yaml.j2
  roles/gitlab/templates/values/00-main.j2
Labels: enhancement

#294 feat: :sparkles: enable argocd applicationset ingress
  roles/argocd/templates/ingress.yaml.j2
Labels: enhancement

#295 fix: :bug: dispatch ingress requests to vault active node
  roles/vault/tasks/main.yml
  roles/vault/templates/ingress.yaml.j2
  roles/vault/templates/role.yaml.j2
  roles/vault/templates/values/00-main.j2
Labels: bug
