Repository cloud-pi-native/socle, pull requests merged in 2025-08, with the labels that each got.

#738 docs: :memo: Update README
  README.md
  cluster-requirements.md
Labels: documentation

#745 feat: :zap: vault pod auto-unseal v0
  roles/gitops/rendering-apps-files/templates/vault/values/200-ansible-job.j2
Labels: enhancement

#770 fix(#768): :bug: infra-keycloak cnpg deployment
  roles/infra/keycloak-infra/tasks/main.yml
  roles/infra/keycloak-infra/templates/pg-cluster-keycloak-nodeport.yaml.j2
  roles/infra/keycloak-infra/templates/pg-cluster-keycloak.yaml.j2
  roles/socle-config/files/config.yaml
  roles/socle-config/files/crd-conf-dso.yaml
Labels: bug
