Repository cloud-pi-native/socle, pull requests merged in 2025-09, with the labels that each got.

#787 fix: :bug: missing cnpg backup ca option
  post-install/pgdump.yaml
  roles/gitops/dso-app/tasks/main.yaml
  roles/gitops/post-install/pgdump/tasks/dump.yml
  roles/gitops/post-install/pgdump/vars/main.yml
  roles/gitops/rendering-apps-files/templates/console/values/100-cnpg.j2
  roles/gitops/rendering-apps-files/templates/gitlab/values/100-cnpg.j2
  roles/gitops/rendering-apps-files/templates/global/templates/bundle-cnpg-s3-secret.yaml.j2
  roles/gitops/rendering-apps-files/templates/global/values/10-platform.j2
  roles/gitops/rendering-apps-files/templates/global/values/200-ansible-job.j2
  roles/gitops/rendering-apps-files/templates/harbor/values/100-cnpg.j2
  roles/gitops/rendering-apps-files/templates/keycloak/values/100-cnpg.j2
  roles/gitops/rendering-apps-files/templates/sonarqube/values/100-cnpg.j2
  roles/socle-config/files/config.yaml
Labels: bug

#775 feat: :technologist: admin-tools pgrestore playbook
  admin-tools/infra-keycloak-admin-password-reset.yaml
  admin-tools/infra-keycloak-user-unlock.yaml
  admin-tools/keycloak-admin-password-reset.yaml
  admin-tools/keycloak-user-unlock.yaml
  admin-tools/pgrestore.yaml
Labels: enhancement

#764 feat: 🔒 disable master realm exposition
  post-install/keycloak.yaml
  roles/gitops/post-install/harbor/tasks/main.yaml
  roles/gitops/post-install/keycloak/tasks/client.yaml
  roles/gitops/post-install/keycloak/tasks/main.yml
  roles/gitops/post-install/keycloak/tasks/sync_users.yml
  roles/gitops/post-install/keycloak/vars/main.yaml
  roles/gitops/post-install/vault/tasks/main.yml
  roles/gitops/rendering-apps-files/tasks/template.yml
  roles/gitops/rendering-apps-files/templates/console/values/00-main.j2
  roles/gitops/rendering-apps-files/templates/keycloak/templates/users.yaml.j2
  roles/gitops/rendering-apps-files/templates/keycloak/values/00-main.j2
  roles/gitops/rendering-apps-files/templates/keycloak/values/200-ansible-job.j2
  roles/gitops/rendering-apps-files/templates/observability/values/00-main.j2
  roles/gitops/rendering-apps-files/templates/sonarqube/values/00-main.j2
  roles/gitops/rendering-apps-files/vars/main.yaml
  roles/socle-config/files/config.yaml
  roles/socle-config/files/cr-conf-dso-default.yaml
  roles/socle-config/files/crd-conf-dso.yaml
  roles/socle-config/files/releases.yaml
  roles/socle-config/tasks/envs.yaml
  versions.md
Labels: enhancement

#829 fix: :bug: vault no-proxy
  roles/gitops/rendering-apps-files/templates/vault/values/10-proxy.j2
Labels: bug

#832 fix: changing targetRevision from main to dsc configured value
  roles/gitops/rendering-apps-files/config/dsc.json.j2
  roles/socle-config/files/cr-conf-dso-default.yaml
Labels: bug

#833 fix: activating post conf mode for awx post conf job
  post-install/awx-oidc.yaml
Labels: bug

#840 fix: :ambulance: Secrets and templates generation
  roles/gitops/rendering-apps-files/tasks/main.yml
  roles/gitops/rendering-apps-files/tasks/template.yml
  roles/gitops/vault-secrets/tasks/main.yaml
  roles/gitops/vault-secrets/tasks/write.yml
Labels: bug, tech

#844 fix: :ambulance: ClusterRoleBindings names for dual install
  roles/gitops/rendering-apps-files/templates/global/templates/cluster-role-binding.yml.j2
  roles/gitops/rendering-apps-files/templates/vault/templates/post-conf-job.yaml.j2
Labels: bug, tech

#853 fix: :ambulance: Argo CD infra plugin config
  roles/gitops/rendering-apps-files/templates/argocd/values/10-metrics.j2
  roles/infra/argocd-infra/templates/vault-plugin-cm.yml.j2
Labels: bug, enhancement, tech

#850 Requirements update ansible modules
  admin-tools/install-requirements.yaml
Labels: bug

#856 fix :bug: missing default values
  .gitignore
  roles/gitops/rendering-apps-files/templates/console/values/10-tls.j2
  roles/gitops/rendering-apps-files/templates/global/templates/cluster-role.yml.j2
  roles/gitops/rendering-apps-files/templates/global/templates/role-binding.yml.j2
  roles/socle-config/files/crd-conf-dso.yaml
Labels: bug, enhancement

#824 docs: 📚 architecture diagram
  README.md
Labels: documentation
