Repository cloud-pi-native/socle, pull requests merged in 2025-05, with the labels that each got.

#556 refactor: recycle: move ingressClassName to common Vault path
  gitops/envs/conf-dso/apps/harbor/values.yaml
  gitops/envs/conf-dso/apps/keycloak/values.yaml
  gitops/envs/conf-dso/apps/observability/values.yaml
  gitops/envs/conf-dso/apps/sonarqube/values.yaml
  gitops/envs/conf-dso/apps/vault/templates/ingress.yaml
  roles/gitops/rendering-apps-files/templates/harbor/values/00-main.j2
  roles/gitops/rendering-apps-files/templates/keycloak/values/00-main.j2
  roles/gitops/rendering-apps-files/templates/observability/values/values.j2
  roles/gitops/rendering-apps-files/templates/sonarqube/values/00-main.j2
  roles/gitops/rendering-apps-files/templates/vault/templates/ingress.yaml.j2
  roles/gitops/vault-secrets/defaults/main.yaml
Labels: enhancement

#558 fix: :bug: GitOps Sonar db username
  gitops/envs/conf-dso/apps/sonarqube/values.yaml
  roles/gitops/rendering-apps-files/templates/sonarqube/values/00-main.j2
  roles/gitops/rendering-apps-files/templates/sonarqube/values/100-cnpg.j2
Labels: bug

#570 Fix/missing conditions infra tools
  admin-tools/get-credentials.yaml
Labels: bug, enhancement

#562 feat: :rocket: add external GitOps repo config
  README.md
  install-gitops.yaml
  roles/gitops/dso-app/tasks/main.yaml
  roles/gitops/dso-app/templates/dso-app.yaml.j2
  roles/gitops/dso-app/templates/dso-appset.yaml.j2
  roles/gitops/local-config/tasks/main.yaml
  roles/gitops/post-install/keycloak/files/group-client-scope-protocolMappers.yaml
  roles/gitops/post-install/keycloak/tasks/main.yml
  roles/gitops/post-install/keycloak/vars/main.yaml
  roles/gitops/rendering-apps-files/tasks/template.yml
  roles/gitops/rendering-apps-files/templates/harbor/values/00-main.j2
  roles/gitops/rendering-apps-files/templates/harbor/values/10-proxy.j2
  roles/gitops/rendering-apps-files/templates/harbor/values/10-registry.j2
  roles/gitops/rendering-apps-files/templates/harbor/values/100-cnpg.j2
  roles/gitops/rendering-apps-files/templates/keycloak/templates/secret-admin.yaml.j2
  roles/gitops/rendering-apps-files/templates/keycloak/values/00-main.j2
  roles/gitops/rendering-apps-files/templates/keycloak/values/10-proxy.j2
  roles/gitops/rendering-apps-files/templates/keycloak/values/10-registry.j2
  roles/gitops/rendering-apps-files/templates/keycloak/values/10-tls.j2
  roles/gitops/rendering-apps-files/templates/keycloak/values/100-cnpg.j2
  roles/gitops/rendering-apps-files/templates/observability/Chart.yaml.j2
  roles/gitops/rendering-apps-files/templates/observability/templates/gitlab-token.yaml.j2
  roles/gitops/rendering-apps-files/templates/observability/templates/grafana-app.yaml.j2
  roles/gitops/rendering-apps-files/templates/observability/templates/observatorium-app.yaml.j2
  roles/gitops/rendering-apps-files/templates/observability/templates/repo-creds.yaml.j2
  roles/gitops/rendering-apps-files/templates/observability/values/values.j2
  roles/gitops/rendering-apps-files/templates/sonarqube/templates/secret-admin.yaml.j2
  roles/gitops/rendering-apps-files/templates/sonarqube/templates/secret-monitoring.yaml.j2
  roles/gitops/rendering-apps-files/templates/sonarqube/values/00-main.j2
  roles/gitops/rendering-apps-files/templates/sonarqube/values/10-proxy.j2
  roles/gitops/rendering-apps-files/templates/sonarqube/values/10-tls.j2
  roles/gitops/rendering-apps-files/templates/sonarqube/values/100-cnpg.j2
  roles/gitops/rendering-apps-files/templates/vault/templates/exposed-ca.yaml.j2
  roles/gitops/rendering-apps-files/templates/vault/templates/ingress.yaml.j2
  roles/gitops/rendering-apps-files/templates/vault/values/00-main.j2
  roles/gitops/rendering-apps-files/templates/vault/values/10-proxy.j2
  roles/gitops/rendering-apps-files/templates/vault/values/10-registry.j2
  roles/gitops/rendering-apps-files/templates/vault/values/100-cpn-backup-utils.j2
  roles/gitops/vault-secrets/tasks/argocd.yml
  roles/gitops/vault-secrets/tasks/main.yaml
  roles/gitops/vault-secrets/tasks/write.yml
  roles/gitops/watchpoint/tasks/main.yaml
  roles/infra/vault-infra/tasks/post-install.yml
  roles/socle-config/files/cr-conf-dso-default.yaml
  roles/socle-config/files/crd-conf-dso.yaml
  roles/socle-config/files/releases.yaml
  roles/socle-config/tasks/main.yaml
  versions.md
Labels: enhancement

#563 feat: :sparkles: Gitlab-runner GitOps deployment
  install-gitops.yaml
  roles/gitops/post-install/gitlabrunner/tasks/main.yml
  roles/gitops/post-install/sonarqube/tasks/main.yaml
  roles/gitops/rendering-apps-files/tasks/main.yml
  roles/gitops/rendering-apps-files/templates/gitlabrunner/Chart.yaml.j2
  roles/gitops/rendering-apps-files/templates/gitlabrunner/templates/gitlab-runner-auth.yaml.j2
  roles/gitops/rendering-apps-files/templates/gitlabrunner/values/00-main.j2
  roles/gitops/rendering-apps-files/templates/gitlabrunner/values/10-exposed-ca.j2
  roles/gitops/rendering-apps-files/templates/gitlabrunner/values/10-proxy.j2
  roles/gitops/rendering-apps-files/templates/gitlabrunner/values/10-registry.j2
  roles/gitops/vault-secrets/defaults/main.yaml
  roles/gitops/vault-secrets/vars/post-install.yaml
Labels: enhancement

#568 feat: :sparkles: Gitlab-ci pipelines exporter GitOps deployment
  README.md
  roles/gitops/rendering-apps-files/tasks/main.yml
  roles/gitops/rendering-apps-files/templates/glexporter/Chart.yaml.j2
  roles/gitops/rendering-apps-files/templates/glexporter/templates/exposed-ca.yaml.j2
  roles/gitops/rendering-apps-files/templates/glexporter/values/00-main.j2
  roles/gitops/rendering-apps-files/templates/glexporter/values/10-exposed-ca.j2
  roles/gitops/rendering-apps-files/templates/glexporter/values/10-proxy.j2
  roles/gitops/rendering-apps-files/templates/glexporter/values/10-registry.j2
  roles/gitops/rendering-apps-files/templates/observability/templates/.grafana-app.yaml.j2.swp
  roles/gitops/vault-secrets/defaults/main.yaml
Labels: enhancement

#555 feat: :sparkles: Argocd GitOps deployment
  README.md
  roles/gitops/rendering-apps-files/tasks/argocd.yml
  roles/gitops/rendering-apps-files/tasks/main.yml
  roles/gitops/rendering-apps-files/tasks/preliminary.yml
  roles/gitops/rendering-apps-files/tasks/template.yml
  roles/gitops/rendering-apps-files/templates/argocd/Chart.yaml.j2
  roles/gitops/rendering-apps-files/templates/argocd/templates/clusterrolebinding-openshift.yml.j2
  roles/gitops/rendering-apps-files/templates/argocd/templates/helm-docker-registry-secret.yml.j2
  roles/gitops/rendering-apps-files/templates/argocd/templates/ingress.yml.j2
  roles/gitops/rendering-apps-files/templates/argocd/templates/prometheusrule.yml.j2
  roles/gitops/rendering-apps-files/templates/argocd/templates/repo-creds.yml.j2
  roles/gitops/rendering-apps-files/templates/argocd/values/00-main.j2
  roles/gitops/rendering-apps-files/templates/argocd/values/10-alerting.j2
  roles/gitops/rendering-apps-files/templates/argocd/values/10-exposed-ca.j2
  roles/gitops/rendering-apps-files/templates/argocd/values/10-metrics.j2
  roles/gitops/rendering-apps-files/templates/argocd/values/10-offline.j2
  roles/gitops/rendering-apps-files/templates/argocd/values/10-proxy.j2
  roles/gitops/rendering-apps-files/templates/argocd/values/10-redis-openshift.j2
  roles/gitops/rendering-apps-files/templates/argocd/values/10-registry.j2
  roles/gitops/rendering-apps-files/templates/observability/templates/.grafana-app.yaml.j2.swp
  roles/gitops/rendering-apps-files/vars/main.yaml
  roles/gitops/vault-secrets/defaults/main.yaml
  roles/infra/argocd-infra/templates/values/00-main.j2
  roles/infra/argocd-infra/templates/values/10-metrics.j2
Labels: enhancement

#582 fix: :wrench: pipe rendering values
  roles/gitops/rendering-apps-files/tasks/parsing.yml
  roles/gitops/rendering-apps-files/tasks/parsing/argocd.yml
  roles/gitops/rendering-apps-files/tasks/parsing/keycloak.yml
  roles/gitops/rendering-apps-files/tasks/parsing/vault.yml
  roles/gitops/rendering-apps-files/tasks/template.yml
  roles/gitops/rendering-apps-files/templates/argocd/values/10-alerting.j2
  roles/gitops/rendering-apps-files/templates/argocd/values/10-metrics.j2
  roles/gitops/rendering-apps-files/templates/keycloak/values/00-main.j2
  roles/gitops/rendering-apps-files/templates/vault/values/00-main.j2
  roles/gitops/rendering-apps-files/vars/main.yaml
Labels: bug

#585 fix: :wrench: existing secrets retrieval for migration
  install-gitops.yaml
  roles/gitops/post-install/harbor/tasks/main.yaml
  roles/gitops/post-install/nexus/tasks/main.yml
  roles/gitops/rendering-apps-files/templates/keycloak/values/00-main.j2
  roles/gitops/rendering-apps-files/templates/keycloak/values/10-registry.j2
  roles/gitops/vault-secrets/defaults/main.yaml
  roles/gitops/vault-secrets/tasks/main.yaml
  roles/gitops/vault-secrets/tasks/write.yml
Labels: bug

#595 chore: :arrow_up: update dso-cnpg chart version
  roles/socle-config/files/releases.yaml
  versions.md
Labels: bug
