Repository cloud-pi-native/socle, pull requests merged in 2025-04, with the labels that each got.

#492 refactor: :recycle: utilization of Helm Chart for CNPG
  gitops/envs/conf-dso/apps/keycloak/Chart.yaml
  gitops/envs/conf-dso/apps/keycloak/templates/pg-cluster-keycloak-backup.yaml
  gitops/envs/conf-dso/apps/keycloak/templates/pg-cluster-keycloak-nodeport.yaml
  gitops/envs/conf-dso/apps/keycloak/templates/pg-cluster-keycloak.yaml
  gitops/envs/conf-dso/apps/keycloak/values.yaml
  roles/gitops/post-install/keycloak/tasks/main.yml
  roles/gitops/rendering-apps-files/templates/keycloak/Chart.yaml.j2
  roles/gitops/rendering-apps-files/templates/keycloak/templates/pg-cluster-keycloak-backup.yaml.j2
  roles/gitops/rendering-apps-files/templates/keycloak/templates/pg-cluster-keycloak-nodeport.yaml.j2
  roles/gitops/rendering-apps-files/templates/keycloak/templates/pg-cluster-keycloak.yaml.j2
  roles/gitops/rendering-apps-files/templates/keycloak/values/100-cnpg.j2
  roles/gitops/vault-secrets/tasks/cnpg-s3-ca.yaml
  roles/gitops/vault-secrets/tasks/main.yaml
  roles/gitops/vault-secrets/vars/main.yaml
  roles/socle-config/files/config.yaml
  roles/socle-config/files/crd-conf-dso.yaml
  roles/socle-config/files/releases.yaml
  versions.md
Labels: enhancement

#497 fix: :wrench: keycloak pod label
  admin-tools/infra-keycloak-user-unlock.yaml
Labels: bug

#499 refactor: :recycle: move keycloak cnpg vault values to common
  gitops/envs/conf-dso/apps/keycloak/values.yaml
  roles/gitops/rendering-apps-files/templates/keycloak/values/100-cnpg.j2
  roles/gitops/vault-secrets/vars/main.yaml
Labels: enhancement

#501 feat: :sparkles: add post-install vault-secrets
  install-gitops.yaml
  roles/gitops/post-install/keycloak/tasks/client.yaml
  roles/gitops/post-install/keycloak/tasks/main.yml
  roles/gitops/vault-secrets/defaults/main.yaml
  roles/gitops/vault-secrets/tasks/argocd.yml
  roles/gitops/vault-secrets/tasks/main.yaml
  roles/gitops/vault-secrets/tasks/write.yml
  roles/gitops/vault-secrets/vars/post-install.yaml
Labels: enhancement

#511 Feat/gitops sonarqube deployment
  gitops/envs/conf-dso/apps/sonarqube/.gitignore
  gitops/envs/conf-dso/apps/sonarqube/Chart.yaml
  gitops/envs/conf-dso/apps/sonarqube/templates/prometheusrule.yml
  gitops/envs/conf-dso/apps/sonarqube/templates/secret-admin.yaml
  gitops/envs/conf-dso/apps/sonarqube/templates/secret-monitoring.yaml
  gitops/envs/conf-dso/apps/sonarqube/values.yaml
  gitops/envs/conf-dso/conf-dso.json
  install-gitops.yaml
  roles/gitops/post-install/sonarqube/tasks/main.yaml
  roles/gitops/post-install/sonarqube/tasks/reset-admin-password.yaml
  roles/gitops/rendering-apps-files/tasks/main.yml
  roles/gitops/rendering-apps-files/templates/sonarqube/Chart.yaml.j2
  roles/gitops/rendering-apps-files/templates/sonarqube/templates/prometheusrule.yml.j2
  roles/gitops/rendering-apps-files/templates/sonarqube/templates/secret-admin.yaml.j2
  roles/gitops/rendering-apps-files/templates/sonarqube/templates/secret-monitoring.yaml.j2
  roles/gitops/rendering-apps-files/templates/sonarqube/values/00-main.j2
  roles/gitops/rendering-apps-files/templates/sonarqube/values/10-offline.j2
  roles/gitops/rendering-apps-files/templates/sonarqube/values/10-platform.j2
  roles/gitops/rendering-apps-files/templates/sonarqube/values/10-proxy.j2
  roles/gitops/rendering-apps-files/templates/sonarqube/values/10-registry.j2
  roles/gitops/rendering-apps-files/templates/sonarqube/values/10-tls.j2
  roles/gitops/rendering-apps-files/templates/sonarqube/values/100-cnpg.j2
  roles/gitops/vault-secrets/defaults/main.yaml
  roles/gitops/vault-secrets/vars/main.yaml
Labels: enhancement

#523 docs: :books: update for GitOps Sonarqube
  README.md
Labels: documentation

#512 Feat/Adapt GitLab Operator install to non cluster scoped
  roles/gitlab-operator/tasks/main.yaml
  roles/gitlab-operator/templates/prometheusrule.yml.j2
  roles/gitlab-operator/templates/values/00-main.j2
  roles/gitlab/tasks/main.yaml
  roles/gitlab/templates/rbac.yaml.j2
  roles/socle-config/files/config.yaml
  roles/socle-config/files/crd-conf-dso.yaml
  uninstall.yaml
Labels: enhancement

#530 feat/Vault Gitops deployment
  README.md
  gitops/envs/conf-dso/apps/vault/Chart.yaml
  gitops/envs/conf-dso/apps/vault/templates/ingress.yaml
  gitops/envs/conf-dso/apps/vault/templates/role.yaml
  gitops/envs/conf-dso/apps/vault/values.yaml
  gitops/envs/conf-dso/conf-dso.json
  install-gitops.yaml
  roles/gitops/post-install/vault/tasks/check.yml
  roles/gitops/post-install/vault/tasks/main.yml
  roles/gitops/post-install/vault/tasks/unseal.yml
  roles/gitops/post-install/vault/templates/superadmin-policy.json.j2
  roles/gitops/rendering-apps-files/tasks/main.yml
  roles/gitops/rendering-apps-files/templates/vault/Chart.yaml.j2
  roles/gitops/rendering-apps-files/templates/vault/templates/exposed-ca.yaml.j2
  roles/gitops/rendering-apps-files/templates/vault/templates/ingress.yaml.j2
  roles/gitops/rendering-apps-files/templates/vault/templates/role.yaml.j2
  roles/gitops/rendering-apps-files/templates/vault/values/00-main.j2
  roles/gitops/rendering-apps-files/templates/vault/values/10-platform.j2
  roles/gitops/rendering-apps-files/templates/vault/values/10-proxy.j2
  roles/gitops/rendering-apps-files/templates/vault/values/10-registry.j2
  roles/gitops/rendering-apps-files/templates/vault/values/100-cpn-backup-utils.j2
  roles/gitops/vault-secrets/defaults/main.yaml
  roles/gitops/vault-secrets/vars/post-install.yaml
  roles/socle-config/files/releases.yaml
Labels: enhancement

#532 fix(1580): Fix Ephemeral storage issue
  roles/gitlab-runner/templates/values/00-main.j2
Labels: bug

#547 Fix/little quick fix
  README.md
  gitops/envs/conf-dso/apps/keycloak/values.yaml
  gitops/envs/conf-dso/apps/sonarqube/values.yaml
  gitops/envs/conf-dso/apps/vault/templates/exposed-ca.yaml
  install-gitops.yaml
  roles/gitops/rendering-apps-files/templates/keycloak/values/00-main.j2
  roles/gitops/rendering-apps-files/templates/sonarqube/values/00-main.j2
Labels: bug, documentation

#526 feat/enable registry-1.docker.io argo login
  roles/argocd/tasks/main.yaml
  roles/argocd/templates/helm-docker-registry-secret.yml.j2
  roles/argocd/templates/values/00-main.j2
  roles/argocd/templates/values/10-proxy.j2
  roles/infra/argocd-infra/tasks/main.yaml
  roles/infra/argocd-infra/templates/helm-docker-registry-secret.yml.j2
  roles/infra/argocd-infra/templates/values/00-main.j2
  roles/socle-config/files/config.yaml
  roles/socle-config/files/crd-conf-dso.yaml
  roles/socle-config/files/releases.yaml
  versions.md
Labels: enhancement
